clients:
    # The total number of clients
    total_clients: 10

    # The number of clients selected in each round
    per_round: 10

    # Whether select variable number of clients per round
    varied: true

    # Should the clients compute test accuracy locally?
    do_test: false
    
    # Whether simulate clients or not
    simulation: false

server:
    address: 127.0.0.1
    port: 8080

data:
    # The training and testing dataset
    datasource: FashionMNIST

    # Where the dataset is located
    data_path: ./data

    # Number of samples in each partition
    partition_size: 200

    # Whether use varied partition per client or not?
    varied: false

    # IID or non-IID?
    sampler: noniid

    # The concentration parameter for the Dirichlet distribution
    concentration: 0.5

    # The random seed for sampling data
    random_seed: 1

trainer:
    # The maximum number of training rounds
    rounds: 50

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The maximum number of clients running concurrently
    max_concurrency: 4

    # The target accuracy
    target_accuracy: 1.0

    # Number of epoches for local training in each communication round
    epochs: 10

    # Whether use varied epochs per client or not?
    varied: false

    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    # The machine learning model
    model_name: lenet5

algorithm:
    # Aggregation algorithm
    type: fedavg

results:
    # Write the following parameter(s) into a CSV
    types: accuracy, training_time, round_time

    # Plot results (x_axis&y_axis)
    plot: round&accuracy, round&training_time, round_time&accuracy, round_time&training_time
